<center><h1 style="color:green">Array Creation</center>

In [5]:
import numpy as np

In [6]:
np.set_printoptions(precision=1,suppress=True)

In [7]:
def create_a_square_invertible_array():
    return np.array([[1,2,1],
                      [3,8,1],
                      [0,4,1]])

In [8]:
def create_my_array():
    return create_a_square_invertible_array()

In [9]:
A = create_my_array()
print(A)

[[1 2 1]
 [3 8 1]
 [0 4 1]]
