In [1]:
import numpy as np,numpy.linalg as npLA

In [2]:
from numpy.linalg import matrix_power

In [3]:
from numpy.testing import assert_allclose,assert_array_less, assert_

In [4]:
from scipy import linalg as LA

In [5]:
from scipy.sparse import csr_matrix

In [6]:
from scipy.linalg import inv,det,expm

In [7]:
import matplotlib.pyplot as plt

In [8]:
np.set_printoptions(precision=1,suppress=True)

# Create Array

In [9]:
def create_a_square_invertible_array():
    return np.array([[1,2,1],
                      [3,8,1],
                      [0,4,1]])

In [10]:
def create_my_array():
    return create_a_square_invertible_array()

In [11]:
A = create_my_array()
print(A)

[[1 2 1]
 [3 8 1]
 [0 4 1]]


# Basic Oprations

## Transpose

## Matrix(1D array)

In [12]:
A = np.arange(3)
print(A)

[0 1 2]


In [13]:
print(A.T)

[0 1 2]


## Matrix(2D array)

In [14]:
A = np.arange(3).reshape((1,3))
print(A)

[[0 1 2]]


In [15]:
print(A.T)

[[0]
 [1]
 [2]]


In [16]:
A = np.arange(1,5).reshape((2,2))
print(A)

[[1 2]
 [3 4]]


In [17]:
print(A.T)

[[1 3]
 [2 4]]


# Inverse

In [18]:
A = np.array([[1,2],
              [3,1]])
Ai = LA.inv(A)
print(Ai)

[[-0.2  0.4]
 [ 0.6 -0.2]]


In [19]:
A = create_my_array()
Ai = LA.inv(A)
print(Ai)

[[ 0.4  0.2 -0.6]
 [-0.3  0.1  0.2]
 [ 1.2 -0.4  0.2]]


## Multiplication

In [20]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [21]:
b = np.array([[3,6,7],
              [1,4,9],
              [2,8,2]])

In [22]:
result = a.dot(b)
print(result)

[[ 11  38  31]
 [ 29  92  85]
 [ 47 146 139]]


In [23]:
matrix1 = csr_matrix([[1, 2, 0], [3, 0, 4], [0, 0, 5]])
matrix2 = csr_matrix([[2, 0, 1], [0, 3, 0], [4, 0, 1]])

In [24]:
result = matrix1.dot(matrix2)
print(result)

  (0, 1)	6
  (0, 2)	1
  (0, 0)	2
  (1, 2)	7
  (1, 0)	22
  (2, 2)	5
  (2, 0)	20


In [25]:
result_dense = result.toarray()

In [26]:
print(result_dense)

[[ 2  6  1]
 [22  0  7]
 [20  0  5]]
