<center><h1 style="color:green">Inverse Matrix</center>

## Definition
The **inverse** of a square matrix $ A $ is another matrix, denoted as $ A^{-1} $, such that their product results in the identity matrix $ I $:

$$
A \cdot A^{-1} = A^{-1} \cdot A = I
$$

where $ I $ is the identity matrix of the same dimension as $ A $.

### Conditions for Inversibility
1. The matrix $ A $ must be a **square matrix** ($ n \times n $).
2. The determinant of $ A $, $ \text{det}(A) $, must not be zero ($ \text{det}(A) \neq 0 $).

If either of these conditions is not satisfied, the matrix is said to be **singular** or **non-invertible**.

---

## Formula for the Inverse

For a $ 2 \times 2 $ matrix:

$$
A = \begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

The inverse is given by:

$$
A^{-1} = \frac{1}{\text{det}(A)} \begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}
$$

where:

$$
\text{det}(A) = ad - bc
$$

For larger matrices ($ n \times n $), the inverse is computed using more advanced methods such as:
- **Gaussian elimination**
- **Adjugate and determinant**:
  $$ A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A) $$
- **Numerical methods** (used in software like NumPy).

---

## Properties of the Inverse

1. **Uniqueness**: The inverse of a matrix is unique.
2. **Double Inverse**:
   $$ (A^{-1})^{-1} = A $$
3. **Transpose of the Inverse**:
   $$ (A^{-1})^T = (A^T)^{-1} $$
4. **Multiplicative Inverse**:
   If \( A \) and \( B \) are invertible matrices, then:
   $$ (A \cdot B)^{-1} = B^{-1} \cdot A^{-1} $$

---

## Example: Inverse of a $ 2 \times 2 $ Matrix

Let:

$$
A = \begin{bmatrix}
4 & 7 \\
2 & 6
\end{bmatrix}
$$

### Step 1: Compute the determinant:
$$
\text{det}(A) = (4)(6) - (7)(2) = 24 - 14 = 10
$$

### Step 2: Compute the inverse:
$$
A^{-1} = \frac{1}{\text{det}(A)} \begin{bmatrix}
6 & -7 \\
-2 & 4
\end{bmatrix}
$$

Substitute $ \text{det}(A) = 10 $:

$$
A^{-1} = \frac{1}{10} \begin{bmatrix}
6 & -7 \\
-2 & 4
\end{bmatrix}
= \begin{bmatrix}
0.6 & -0.7 \\
-0.2 & 0.4
\end{bmatrix}
$$

---

## Example: Inverse of a $ 3 \times 3 $ Matrix

Let:

$$
A = \begin{bmatrix}
2 & 1 & 1 \\
1 & 3 & 2 \\
1 & 0 & 0
\end{bmatrix}
$$

### Step 1: Compute the determinant
The determinant of a $ 3 \times 3 $ matrix is computed as:

$$
\text{det}(A) = a_{11} \cdot \text{det} \begin{bmatrix} a_{22} & a_{23} \\ a_{32} & a_{33} \end{bmatrix}
- a_{12} \cdot \text{det} \begin{bmatrix} a_{21} & a_{23} \\ a_{31} & a_{33} \end{bmatrix}
+ a_{13} \cdot \text{det} \begin{bmatrix} a_{21} & a_{22} \\ a_{31} & a_{32} \end{bmatrix}
$$

Substituting the elements of $ A $:

$$
\text{det}(A) = 2 \cdot \text{det} \begin{bmatrix} 3 & 2 \\ 0 & 0 \end{bmatrix}
- 1 \cdot \text{det} \begin{bmatrix} 1 & 2 \\ 1 & 0 \end{bmatrix}
+ 1 \cdot \text{det} \begin{bmatrix} 1 & 3 \\ 1 & 0 \end{bmatrix}
$$

Compute the determinants of the $ 2 \times 2 $ submatrices:

$$
\text{det} \begin{bmatrix} 3 & 2 \\ 0 & 0 \end{bmatrix} = (3)(0) - (2)(0) = 0
$$

$$
\text{det} \begin{bmatrix} 1 & 2 \\ 1 & 0 \end{bmatrix} = (1)(0) - (2)(1) = -2
$$

$$
\text{det} \begin{bmatrix} 1 & 3 \\ 1 & 0 \end{bmatrix} = (1)(0) - (3)(1) = -3
$$

Substitute back:

$$
\text{det}(A) = 2(0) - 1(-2) + 1(-3) = 0 + 2 - 3 = -1
$$

Thus, $ \text{det}(A) = -1 $, so the matrix is invertible.

---

### Step 2: Compute the adjugate matrix (Adj(A))

The adjugate matrix is the transpose of the cofactor matrix. Compute the cofactors of \( A \):

#### First Row:
- $ \text{Cofactor}(a_{11}) = \text{det} \begin{bmatrix} 3 & 2 \\ 0 & 0 \end{bmatrix} = 0 $
- $ \text{Cofactor}(a_{12}) = -\text{det} \begin{bmatrix} 1 & 2 \\ 1 & 0 \end{bmatrix} = -(-2) = 2 $
- $ \text{Cofactor}(a_{13}) = \text{det} \begin{bmatrix} 1 & 3 \\ 1 & 0 \end{bmatrix} = -3 $

#### Second Row:
- $ \text{Cofactor}(a_{21}) = -\text{det} \begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix} = 0 $
- $ \text{Cofactor}(a_{22}) = \text{det} \begin{bmatrix} 2 & 1 \\ 1 & 0 \end{bmatrix} = -1 $
- $ \text{Cofactor}(a_{23}) = -\text{det} \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix} = -5 $

#### Third Row:
- $ \text{Cofactor}(a_{31}) = \text{det} \begin{bmatrix} 1 & 1 \\ 3 & 2 \end{bmatrix} = -1 $
- $ \text{Cofactor}(a_{32}) = -\text{det} \begin{bmatrix} 2 & 1 \\ 1 & 0 \end{bmatrix} = 1 $
- $ \text{Cofactor}(a_{33}) = \text{det} \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix} = 5 $

The cofactor matrix is:

$$
\text{Cofactor}(A) = \begin{bmatrix}
0 & 2 & -3 \\
0 & -1 & -5 \\
-1 & 1 & 5
\end{bmatrix}
$$

The adjugate matrix is the transpose:

$$
\text{Adj}(A) = \begin{bmatrix}
0 & 0 & -1 \\
2 & -1 & 1 \\
-3 & -5 & 5
\end{bmatrix}
$$

---

### Step 3: Compute the inverse
The inverse is given by:

$$
A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{Adj}(A)
$$

Substitute $ \text{det}(A) = -1 $:

$$
A^{-1} = -1 \cdot \begin{bmatrix}
0 & 0 & -1 \\
2 & -1 & 1 \\
-3 & -5 & 5
\end{bmatrix}
$$

Simplify:

$$
A^{-1} = \begin{bmatrix}
0 & 0 & 1 \\
-2 & 1 & -1 \\
3 & 5 & -5
\end{bmatrix}
$$

---

<h1>Python Implementation

<b>Here’s how we can compute the inverse of a $ 3 \times 3 $ matrix programmatically.

In [1]:
import numpy as np

# Define a 3x3 matrix
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

# Compute the inverse
A_inverse = np.linalg.inv(A)

print("Original Matrix:")
print(A)
print("\nInverse of the Matrix:")
print(A_inverse)

Original Matrix:
[[2 1 1]
 [1 3 2]
 [1 0 0]]

Inverse of the Matrix:
[[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]
