<center><h1 style="color:green">LU Decomposition</center>

## Definition:
LU decomposition (or LU factorization) is a method of decomposing a square matrix $ A $ into the product of two triangular matrices:
1. **$ L $:** A lower triangular matrix (with ones on the diagonal),
2. **$ U $:** An upper triangular matrix.

For a square matrix $ A $, we can write:
$$
A = LU
$$
where:
- $ L $ is a lower triangular matrix, and
- $ U $ is an upper triangular matrix.

If partial pivoting is applied (to ensure numerical stability), the decomposition becomes:
$$
PA = LU
$$
where $ P $ is a permutation matrix that accounts for row swaps.

---

## Applications of LU Decomposition:
1. **Solving Linear Systems ($ Ax = b $):**
   - Decompose $ A $ into $ L $ and $ U $.
   - Solve $ Ly = b $ using **forward substitution** (solve for $ y $).
   - Solve $ Ux = y $ using **back substitution** (solve for $ x $).

2. **Determinant Calculation:**
   - If $ A = LU $, the determinant is calculated as:
     $$
     \text{det}(A) = \text{det}(L) \cdot \text{det}(U)
     $$
   - Since $ L $ is lower triangular with ones on its diagonal, $ \text{det}(L) = 1 $, so:
     $$
     \text{det}(A) = \prod \text{diagonal entries of } U
     $$

3. **Matrix Inversion:**
   - To compute $ A^{-1} $, decompose $ A = LU $, then solve $ LUx = I $ column by column, where $ I $ is the identity matrix.

---

In [3]:
import numpy as np
from scipy.linalg import lu

In [5]:
A = np.array([[2,5,6],
            [6,7,8],
            [1,8,4]])

<b>LU Decomposition

In [6]:
P,L,U = lu(A)

<b>Permutation Matrix

In [9]:
print(P)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


<b>Lower Triangular Matrix

In [10]:
print(L)

[[1.         0.         0.        ]
 [0.16666667 1.         0.        ]
 [0.33333333 0.3902439  1.        ]]


<b>Upper Triangular Matrix

In [11]:
print(U)

[[6.         7.         8.        ]
 [0.         6.83333333 2.66666667]
 [0.         0.         2.29268293]]


<b>Reconstruct A matrix

In [16]:
res = L.dot(U)

In [17]:
res

array([[6., 7., 8.],
       [1., 8., 4.],
       [2., 5., 6.]])

In [18]:
res = P.dot(res)

In [19]:
res

array([[2., 5., 6.],
       [6., 7., 8.],
       [1., 8., 4.]])

In [22]:
res = P.dot(L.dot(U))
res

array([[2., 5., 6.],
       [6., 7., 8.],
       [1., 8., 4.]])

In [23]:
ans = P@L@U
ans

array([[2., 5., 6.],
       [6., 7., 8.],
       [1., 8., 4.]])