<center><h1 style="color:green">Transpose</center>

## Definition
The **transpose** of a matrix is obtained by flipping the matrix over its diagonal. This means that the row indices of the elements become the column indices, and the column indices become the row indices.

If a matrix $ A $ is of order $ m \times n $, then its transpose $ A^T $ (or $ A^\top $) will be of order $ n \times m $.

### Mathematically:
For a matrix $ A $ with elements $ a_{ij} $:

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{bmatrix}
$$

The transpose \( A^T \) is:

$$
A^T = \begin{bmatrix}
a_{11} & a_{21} & \dots & a_{m1} \\
a_{12} & a_{22} & \dots & a_{m2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1n} & a_{2n} & \dots & a_{mn}
\end{bmatrix}
$$

---

## Properties of the Transpose

1. **Double Transpose:** The transpose of the transpose of a matrix is the original matrix.

$$
(A^T)^T = A
$$

2. **Addition Property:** The transpose of the sum of two matrices is the sum of their transposes.

$$
(A + B)^T = A^T + B^T
$$

3. **Multiplication Property:** The transpose of the product of two matrices is the product of their transposes, in reverse order.

$$
(A \cdot B)^T = B^T \cdot A^T
$$

4. **Scalar Multiplication:** The transpose of a scalar multiplied by a matrix is the scalar multiplied by the transpose.

$$
(cA)^T = cA^T
$$

5. **Symmetric Matrix:** A matrix is symmetric if:

$$
A = A^T
$$

---

## Example

Let:

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

The transpose of \( A \), denoted as \( A^T \), is:

$$
A^T = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$$

---

In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=1,suppress=True)

In [3]:
def create_a_square_invertible_array():
    return np.array([[1,2,1],
                      [3,8,1],
                      [0,4,1]])

In [4]:
def create_my_array():
    return create_a_square_invertible_array()

In [5]:
A = create_my_array()
print(A)

[[1 2 1]
 [3 8 1]
 [0 4 1]]


<b>Matrix Transpose for(1D Array)

In [6]:
A = np.arange(3)
print(A)

[0 1 2]


In [7]:
print(A.T)

[0 1 2]


<b>Matrix Transpose for(2D Array)

In [8]:
A = np.arange(3).reshape((1,3))
print(A)

[[0 1 2]]


In [9]:
print(A.T)

[[0]
 [1]
 [2]]


In [10]:
A = np.arange(1,10).reshape((3,3))
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


<b>Python Implementation

In [12]:
# Define a matrix
A = [[1, 2, 3],
     [4, 5, 6]]

# Compute the transpose manually
A_transpose = [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

print("Original Matrix:")
for row in A:
    print(row)

print("\nTranspose of the Matrix:")
for row in A_transpose:
    print(row)


Original Matrix:
[1, 2, 3]
[4, 5, 6]

Transpose of the Matrix:
[1, 4]
[2, 5]
[3, 6]
